### ISSUE TITLE
Install instructions - package name? (Stata)

### ISSUE THREAD

**Issue by felixpoege** [nppackages/scpi#2]
Hi all,
I wanted to try the package out, but I'm stuck with getting it to run in Stata 17. I installed it using `net install` and now I am getting the following error (in Stata) when running `scdata`: `ModuleNotFoundError: No module named 'scpi_pkg'`
Now, when I try to run `pip install scpi_pkg` in a Python console, I get the error `ERROR: Could not find a version that satisfies the requirement scpi_pkg`. In contrast, `pip install scpi` worked flawlessly.
What am I overlooking?
Thank you!

**Comment by mdcattaneo** [comment]
Hi Felix:

Please repost your question using our mailing list here:

https://nppackages.github.io/scpi/

Furthermore, in the website above there is a detailed explanation on how to
install SCPI in Stata and Python.

Best wishes,

Matias

**Comment by felixpoege** [comment]
Sure, I can do that. I followed the instructions given on that website. Thanks!
